spring:
  application:
    name: users-service
server:
  port: 8762
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health'
keycloak:
  serverUrl: http://localhost:8760/
  clientId: users-service
  clientSecret: jftzuKCciHm8bfJ2V0bZK2qtMrXivBgA
  userRealm: delivery
  connectionPoolSize: 20