server:
  port: 8762
spring:
  application:
    name: users-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope: openid
            authorization-grant-type: authorization_code
            client-id: delivery-ui
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/delivery
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/delivery
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health'
app:
  keycloak:
    baseUrl: http://localhost:8080/
    clientId: users-service
    clientSecret: jftzuKCciHm8bfJ2V0bZK2qtMrXivBgA
    realm: delivery
    connectionPoolSize: 20
#logging:
  #level:
    #org.springframework.security: TRACE
    #org.springframework.security.oauth2: TRACE
    #org.keycloak: TRACE