server:
  port: 8763
spring:
  application:
    name: restaurants-service
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurants_db
    username: restaurantsservice
    password: restaurantsservice
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/