server:
  port: 8084
spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: ordersservice
    password: ordersservice
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    show-sql: false
    hibernate:
      format_sql: false
      type: trace
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    org:
      hibernate:
        SQL: INFO #DEBUG
        orm:
          jdbc:
            bind: INFO #TRACE
        type:
          descriptor:
            sql:
              BasicBinder: INFO #TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
app:
  gateway:
    baseUrl: http://localhost:8099
  client:
    users-service:
      baseUrl: ${app.gateway.baseUrl}/users-service
    restaurants-service:
      baseUrl: ${app.gateway.baseUrl}/restaurants-service
    menus-service:
      baseUrl: ${app.gateway.baseUrl}/menus-service