server:
  port: 8081
spring:
  application:
    name: web-ui
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: delivery-ui
            #client-secret: hwdX94y90HQC0VcUIUTROMKYnsYAaEPI
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/delivery
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/delivery
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
app:
  client:
    gateway:
      baseUrl: http://localhost:8082
logging:
  level:
    dev:
      thiagooliveira:
        delivery: DEBUG