server:
  port: 8081
spring:
  application:
    name: web-ui
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: delivery-ui
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${app.keycloak.baseUrl}/realms/delivery
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.baseUrl}/realms/delivery
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
app:
  keycloak:
    baseUrl: http://localhost:8080
  client:
    gateway:
      baseUrl: http://localhost:8082
logging:
  level:
    dev.thiagooliveira.delivery: DEBUG