spring:
  application:
    name: notifications-service
server:
  port: 8766
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    dev.thiagooliveira.delivery: DEBUG