server:
  port: 8766
info:
  app:
    name: ${spring.application.name}
    description: Responsible for notifications
    version: 0.0.1-SNAPSHOT
    author: Thiago Oliveira
spring:
  application:
    name: notifications-service
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    dev.thiagooliveira.delivery: DEBUG