openapi: 3.0.0
info:
  title: Restaurant API
  version: 1.0.0
paths:
  /restaurants:
    get:
      tags:
        - Restaurant
      summary: Get a paginated list of restaurants
      description: Retrieve a paginated list of restaurants.
      operationId: getRestaurants
      parameters:
        - name: pageNumber
          in: query
          description: The page number to retrieve
          schema:
            type: integer
            format: int32
            default: 0
        - name: pageSize
          in: query
          description: The number of items per page
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        '200':
          description: Successful response with a paginated list of restaurants
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestaurantPage'
        '400':
          description: Bad request, e.g., invalid pageNumber or pageSize
        '500':
          description: Internal server error
  /restaurants/{id}:
    get:
      tags:
        - Restaurant
      summary: Get restaurant by ID
      description: Retrieve details of a specific restaurant by its ID.
      operationId: getRestaurantById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the restaurant to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response with restaurant details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurant'
        '404':
          description: Restaurant not found
        '500':
          description: Internal server error
components:
  schemas:
    Pageable:
      type: object
      properties:
        sort:
          $ref: '#/components/schemas/Sort'
        offset:
          type: integer
          description: Current offset
        pageNumber:
          type: integer
          description: Current page number
        pageSize:
          type: integer
          description: Number of elements per page
        unpaged:
          type: boolean
          description: Indicates if this is a pageable request
        paged:
          type: boolean
          description: Indicates if this is a paged request
    Sort:
      type: object
      properties:
        sorted:
          type: boolean
          description: Indicates if sorting is enabled
        unsorted:
          type: boolean
          description: Indicates if sorting is not enabled
        empty:
          type: boolean
          description: Indicates if the sort is empty
    PageRequest:
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
          description: The page number to retrieve
          default: 0
        pageSize:
          type: integer
          format: int32
          description: The number of items per page
          default: 10
    RestaurantPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Restaurant'
        pageable:
          $ref: '#/components/schemas/Pageable'
        totalPages:
          type: integer
          description: Total number of pages
        totalElements:
          type: integer
          description: Total number of elements
        last:
          type: boolean
          description: Indicates if this is the last page
        size:
          type: integer
          description: Number of elements per page
        number:
          type: integer
          description: Current page number
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
          description: Indicates if this is the first page
        numberOfElements:
          type: integer
          description: Number of elements currently on this page
    Restaurant:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          nullable: false
        description:
          type: string
        phoneNumber:
          type: string
          nullable: false
        address:
          type: object
          properties:
            street:
              type: string
            number:
              type: string
            state:
              type: string
              nullable: false
            postalCode:
              type: string
            country:
              type: string
              nullable: false
            notes:
              type: string